# Generated by nix-init
{
  lib,
  buildGoModule,
  fetchFromGitHub,
}:
buildGoModule rec {
  pname = "cloud-tasks-emulator";
  version = "1.2.0";

  src = fetchFromGitHub {
    owner = "aertje";
    repo = "cloud-tasks-emulator";
    rev = "v${version}";
    hash = "sha256-Zf4mUSnlvAbd86RL5mkKYc2Ykcj5mfeYFxIuBmvs05U=";
  };

  vendorHash = "sha256-jThPgALga/mhLW5zNKEj8vcge7HbbFGZHTRTc2ALIP0=";
  subPackages = [ "." ];
  ldflags = ["-s" "-w"];

  meta = {
    description = "Google cloud tasks emulator";
    homepage = "https://github.com/aertje/cloud-tasks-emulator";
    license = lib.licenses.mit;
    mainProgram = "cloud-tasks-emulator";
  };
}
