# Generated by nix-init
{
  src,
  lib,
  buildGoModule,
}:
buildGoModule rec {
  pname = "cloud-tasks-emulator";

  inherit src;

  version = src.shortRev;

  vendorHash = "sha256-jThPgALga/mhLW5zNKEj8vcge7HbbFGZHTRTc2ALIP0=";
  subPackages = ["."];
  ldflags = ["-s" "-w"];

  meta = {
    description = "Google cloud tasks emulator";
    homepage = "https://github.com/aertje/cloud-tasks-emulator";
    license = lib.licenses.mit;
    mainProgram = "cloud-tasks-emulator";
  };
}
